## Import Tensorflow.

In [3]:
import tensorflow as tf

## Check the versions.

In [4]:
print('Tensorflow version :-',tf.__version__)

Tensorflow version :- 2.0.0


In [6]:
print('Tensorflow version :-',tf.keras.__version__)

Tensorflow version :- 2.2.4-tf


## CPU/GPU Check..

In [7]:
variable = tf.Variable([3,3])
if tf.test.is_gpu_available():
    print('GPU')
    print('GPU #0?')
    print(var.device.endwith('GPU : 0'))
else:
    print('CPU')

CPU


### Tensor Constant

In [8]:
variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 3])>

In [9]:
type(variable)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [10]:
Nero = tf.constant(42)

In [11]:
Nero

<tf.Tensor: id=9, shape=(), dtype=int32, numpy=42>

In [12]:
type(Nero)

tensorflow.python.framework.ops.EagerTensor

In [14]:
Nero.numpy()

42

In [17]:
Nero.dtype,Nero.shape

(tf.int32, TensorShape([]))

In [18]:
neron1 = tf.constant(1,dtype=tf.int32)

In [19]:
neron1

<tf.Tensor: id=10, shape=(), dtype=int32, numpy=1>

In [21]:
neron2 = tf.constant([[22,45],[12,89]],dtype=tf.int16)

In [22]:
neron2

<tf.Tensor: id=12, shape=(2, 2), dtype=int16, numpy=
array([[22, 45],
       [12, 89]], dtype=int16)>

In [23]:
neron2.numpy()

array([[22, 45],
       [12, 89]], dtype=int16)

In [24]:
neron2.shape

TensorShape([2, 2])

## Tensorflow wth Once and Zeros.

In [25]:
zeros=tf.zeros([2,2],dtype=tf.int32)

In [26]:
zeros

<tf.Tensor: id=15, shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]])>

In [27]:
zeros.numpy()

array([[0, 0],
       [0, 0]])

In [28]:
zeros.shape

TensorShape([2, 2])

In [29]:
cost1 = tf.constant([[22,33],[23,44],[2233,444]])
cost2 = tf.constant([[22,34],[22,89],[55,21]])

Add_costants = tf.add(cost1,cost2)
print(Add_costants)

tf.Tensor(
[[  44   67]
 [  45  133]
 [2288  465]], shape=(3, 2), dtype=int32)


## Random Constant.

In [30]:
tf.random.normal([2,2],mean=0,stddev=1)  #It is following the gaussion distribution where the mean =0 and std =1

<tf.Tensor: id=42, shape=(2, 2), dtype=float32, numpy=
array([[ 0.28745618,  0.35560083],
       [-0.23269996, -0.38982865]], dtype=float32)>

In [31]:
tf.random.uniform([2,2],minval=0,maxval=10,dtype=tf.int32)  #given the data inbetween the 0 to 10.

<tf.Tensor: id=46, shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [0, 9]])>

## Variable

It is kind of intialization of values which will store in the temporary basis in the variable.

In [33]:
var1 =110   #Python  Variable
var1

110

In [34]:
var2 = tf.Variable(11)
var2

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=11>

In [35]:
var3= tf.Variable([[12,23,45],[234,43,45],[22,97,34]])

In [36]:
var3

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[ 12,  23,  45],
       [234,  43,  45],
       [ 22,  97,  34]])>

## To Reassigne the variable use var.assign()

In [37]:
var = tf.Variable(12)

In [39]:
var.assign(223)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=223>

In [40]:
var

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=223>

## Rank,Reshape,shape

In [44]:
tensor = tf.constant([[12,34,45],[344,545,55],[22,54,66],[11,22,33]])

In [45]:
tensor.shape

TensorShape([4, 3])

In [46]:
tf.reshape(tensor,[3,4])

<tf.Tensor: id=78, shape=(3, 4), dtype=int32, numpy=
array([[ 12,  34,  45, 344],
       [545,  55,  22,  54],
       [ 66,  11,  22,  33]])>

In [47]:
tf.rank(tensor)

<tf.Tensor: id=79, shape=(), dtype=int32, numpy=2>

## Slicing data 

In [60]:
slicer=tensor[1,2]  #0 rows and 2 is the columns
slicer

<tf.Tensor: id=113, shape=(), dtype=int32, numpy=55>

In [61]:
tensor

<tf.Tensor: id=76, shape=(4, 3), dtype=int32, numpy=
array([[ 12,  34,  45],
       [344, 545,  55],
       [ 22,  54,  66],
       [ 11,  22,  33]])>

## Casting the data to the numpy variable.

In [62]:
print(tensor.numpy())

[[ 12  34  45]
 [344 545  55]
 [ 22  54  66]
 [ 11  22  33]]


In [67]:
print(tensor[0,1].numpy())

34


### Size

In [69]:
size = tf.size(input=tensor)
print(size.numpy())

12


## Mathematical Operation.

In [70]:
a = tf.random.normal([2,2])
b = tf.random.uniform([2,2])
add = a+b
print(add)

tf.Tensor(
[[ 1.1859223   0.5108549 ]
 [-0.8499588  -0.09984362]], shape=(2, 2), dtype=float32)


In [71]:
c = tf.sqrt(a)
d = tf.exp(b)
print(c)

tf.Tensor(
[[0.61656815 0.67398417]
 [       nan        nan]], shape=(2, 2), dtype=float32)


In [72]:
print(d)

tf.Tensor(
[[2.2384105 1.0582327]
 [1.2750354 1.7873431]], shape=(2, 2), dtype=float32)


In [73]:
tensorflow = tensor*tensor
tensorflow

<tf.Tensor: id=150, shape=(4, 3), dtype=int32, numpy=
array([[   144,   1156,   2025],
       [118336, 297025,   3025],
       [   484,   2916,   4356],
       [   121,    484,   1089]])>

## Broadcasting..

In [74]:
tensor4 = tensor*4
tensor4

<tf.Tensor: id=152, shape=(4, 3), dtype=int32, numpy=
array([[  48,  136,  180],
       [1376, 2180,  220],
       [  88,  216,  264],
       [  44,   88,  132]])>

## Matrix Multiplication and Transpose of Matrix

In [75]:
tf.matmul(tensor,tensor4,transpose_a=True)

<tf.Tensor: id=153, shape=(3, 3), dtype=int32, numpy=
array([[ 476340,  757272,   85100],
       [ 757272, 1206324,  143180],
       [  85100,  143180,   41980]])>

In [76]:
tf.matmul(tensor,tensor4,transpose_b=True)

<tf.Tensor: id=154, shape=(4, 4), dtype=int32, numpy=
array([[  13300,  100532,   20280,    9460],
       [ 100532, 1673544,  162512,   70356],
       [  20280,  162512,   31024,   14432],
       [   9460,   70356,   14432,    6776]])>

In [77]:
tf.transpose(tensor)

<tf.Tensor: id=156, shape=(3, 4), dtype=int32, numpy=
array([[ 12, 344,  22,  11],
       [ 34, 545,  54,  22],
       [ 45,  55,  66,  33]])>

## Cast the Matrix with some other dtypes

In [78]:
tf.cast(tensor,dtype=tf.float16)

<tf.Tensor: id=157, shape=(4, 3), dtype=float16, numpy=
array([[ 12.,  34.,  45.],
       [344., 545.,  55.],
       [ 22.,  54.,  66.],
       [ 11.,  22.,  33.]], dtype=float16)>

## Ragged Tensors

In [82]:
ragged = tf.ragged.constant([[2,34,55],[23,55,66],[44,24,53],[0],[2]])

#If will not return an error after the disimilarity found in the arrayes ==> Ragged array

In [84]:
print(ragged)

<tf.RaggedTensor [[2, 34, 55], [23, 55, 66], [44, 24, 53], [0], [2]]>


In [89]:
print(ragged[:1])
print(ragged[1:2])
print(ragged[2:3])
print(ragged[3:4])
print(ragged[4:5])

<tf.RaggedTensor [[2, 34, 55]]>
<tf.RaggedTensor [[23, 55, 66]]>
<tf.RaggedTensor [[44, 24, 53]]>
<tf.RaggedTensor [[0]]>
<tf.RaggedTensor [[2]]>


## Squred Difference 

In [90]:
tf.math.squared_difference(tensor,tensor4)

<tf.Tensor: id=822, shape=(4, 3), dtype=int32, numpy=
array([[   1296,   10404,   18225],
       [1065024, 2673225,   27225],
       [   4356,   26244,   39204],
       [   1089,    4356,    9801]])>

## Mean Calculation.

In [91]:
#mean for all axes
tf.reduce_mean(tensor)  #default axes =None

<tf.Tensor: id=824, shape=(), dtype=int32, numpy=103>

In [92]:
tf.reduce_mean(tensor,axis=1)

<tf.Tensor: id=826, shape=(4,), dtype=int32, numpy=array([ 30, 314,  47,  22])>

In [93]:
tf.reduce_mean(tensor,axis=0)

<tf.Tensor: id=828, shape=(3,), dtype=int32, numpy=array([ 97, 163,  49])>

In [94]:
tf.reduce_mean(tensor,axis=0,keepdims=True)

<tf.Tensor: id=830, shape=(1, 3), dtype=int32, numpy=array([[ 97, 163,  49]])>

## Random Function in Tensorflow

In [95]:
tf.random.uniform([2,2])

<tf.Tensor: id=837, shape=(2, 2), dtype=float32, numpy=
array([[0.3448739, 0.7109643],
       [0.5705409, 0.4586686]], dtype=float32)>

In [96]:
tf.random.normal([2,2])

<tf.Tensor: id=843, shape=(2, 2), dtype=float32, numpy=
array([[ 0.35931388, -0.09166675],
       [ 2.1867166 , -0.6822234 ]], dtype=float32)>

## Random Function with set_seed()

In [98]:
tf.random.set_seed(10)
aa=tf.random.uniform([2,2])
bb =tf.random.normal([2,2])

In [101]:
print(aa)

tf.Tensor(
[[0.644151  0.8082472]
 [0.8976548 0.6368902]], shape=(2, 2), dtype=float32)


In [102]:
print(bb)

tf.Tensor(
[[ 0.4831794  -0.97205937]
 [-1.8948057  -0.5673938 ]], shape=(2, 2), dtype=float32)


### Cancat

In [103]:
x=tensor 
y = tensor*19
final=x+y

In [104]:
final_matrix = tf.concat([x,y,final],axis=1)

In [105]:
final_matrix

<tf.Tensor: id=861, shape=(4, 9), dtype=int32, numpy=
array([[   12,    34,    45,   228,   646,   855,   240,   680,   900],
       [  344,   545,    55,  6536, 10355,  1045,  6880, 10900,  1100],
       [   22,    54,    66,   418,  1026,  1254,   440,  1080,  1320],
       [   11,    22,    33,   209,   418,   627,   220,   440,   660]])>

## argmax,argmin

In [108]:
a=tf.argmax(tensor.numpy().flatten())

In [109]:
print(a)

tf.Tensor(4, shape=(), dtype=int64)


In [112]:
tensor.numpy().flatten()[a]

545

In [110]:
b=tf.argmin(tensor.numpy().flatten())

In [113]:
tensor.numpy().flatten()[b]

11

In [111]:
print(b)

tf.Tensor(9, shape=(), dtype=int64)


## Saving and Restoring using the Checkpoint

To restore the data whenever we wanted.

In [114]:
variable = tf.Variable([[12,34,45],[23,45,6]])

In [116]:
checkpoints= tf.train.Checkpoint(var=variable)

In [117]:
savepath = checkpoints.save('./vars')

In [120]:
variable.assign([[3,3,4],[2,4,5]])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[3, 3, 4],
       [2, 4, 5]])>

In [123]:
checkpoints.restore(savepath)
print(variable)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[12, 34, 45],
       [23, 45,  6]])>


## tf.function

In [125]:
def f1(x,y):
    return tf.reduce_mean(input_tensor=tf.multiply(x**3,6)+ y**3)

fuc = tf.function(f1)

x = tf.constant([11,23,44])
y = tf.constant([22,34,55])

assert f1(x,y).numpy() == fuc(x,y).numpy()


In [126]:
fuc(10,22)

<tf.Tensor: id=964, shape=(), dtype=int32, numpy=16648>

## GradientTape

In [127]:
a = tf.random.normal([2,2])
b = tf.random.normal([2,2])

with tf.GradientTape() as tape:  #Record operations for automatic differentiation.
    tape.watch(a)              #Ensures that `tensor` is being traced by this tape.
    c = tf.sqrt(tf.square(a)+tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[-0.33435947 -0.96524227]
 [ 0.8265694  -0.94369376]], shape=(2, 2), dtype=float32)


## Keras,High Level API For the Tensorflow==2.0.0

## Thank You !!